server {
 listen 80;
 root /usr/share/nginx/html;
 resolver 127.0.0.11 valid=10s;
 location / { try_files $uri $uri/ /index.html; }
 location /insider-api/ {
  set $insider insiderpulse:8011;
  rewrite ^/insider-api/(.*)$ /$1 break;
  proxy_pass http://$insider;
  proxy_connect_timeout 2s;
  proxy_read_timeout 15s;
 }
 location /aster-api/ {
  set $aster gateway:8010;
  rewrite ^/aster-api/(.*)$ /$1 break;
  proxy_pass http://$aster;
  proxy_connect_timeout 2s;
  proxy_read_timeout 5s;
 }
}
